swagger: "2.0"
info:
  title: Weather Service
  description: Service for weather information.
  version: ""
host: dev.myweatherdomain.com
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /liveness:
    get:
      tags:
      - healthcheck
      summary: liveness healthcheck
      operationId: healthcheck#liveness
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/HealthcheckLivenessResponseBody'
            required:
            - status
      schemes:
      - https
  /readiness:
    get:
      tags:
      - healthcheck
      summary: readiness healthcheck
      operationId: healthcheck#readiness
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/HealthcheckReadinessResponseBody'
            required:
            - status
        "503":
          description: Service Unavailable response.
          schema:
            $ref: '#/definitions/HealthcheckReadinessServiceUnavailableErrorResponseBody'
            required:
            - status
      schemes:
      - https
  /v1/weather:
    post:
      tags:
      - weather
      summary: WeatherQuery weather
      operationId: weather#WeatherQuery
      parameters:
      - name: WeatherQueryRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/WeatherWeatherQueryRequestBody'
          required:
          - lat
          - lon
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/WeatherWeatherQueryOKResponseBody'
            required:
            - temp
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/WeatherWeatherQueryBadRequestResponseBody'
            required:
            - temp
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/WeatherWeatherQueryInternalServerErrorResponseBody'
            required:
            - temp
      schemes:
      - https
definitions:
  HealthcheckLivenessResponseBody:
    title: HealthcheckLivenessResponseBody
    type: object
    properties:
      status:
        type: string
        example: up
    example:
      status: up
    required:
    - status
  HealthcheckReadinessResponseBody:
    title: HealthcheckReadinessResponseBody
    type: object
    properties:
      status:
        type: string
        example: up
    example:
      status: up
    required:
    - status
  HealthcheckReadinessServiceUnavailableErrorResponseBody:
    title: HealthcheckReadinessServiceUnavailableErrorResponseBody
    type: object
    properties:
      status:
        type: string
        example: status
    example:
      status: status
    required:
    - status
  WeatherWeatherQueryBadRequestResponseBody:
    title: WeatherWeatherQueryBadRequestResponseBody
    type: object
    properties:
      feels_like:
        type: number
        example: 22.1
        format: double
      pressure:
        type: integer
        example: 1024
        format: int64
      temp:
        type: number
        example: 23.4
        format: double
      wind_speed:
        type: integer
        example: 10
        format: int64
    example:
      feels_like: 22.1
      pressure: 1024
      temp: 23.4
      wind_speed: 10
    required:
    - temp
  WeatherWeatherQueryInternalServerErrorResponseBody:
    title: WeatherWeatherQueryInternalServerErrorResponseBody
    type: object
    properties:
      feels_like:
        type: number
        example: 22.1
        format: double
      pressure:
        type: integer
        example: 1024
        format: int64
      temp:
        type: number
        example: 23.4
        format: double
      wind_speed:
        type: integer
        example: 10
        format: int64
    example:
      feels_like: 22.1
      pressure: 1024
      temp: 23.4
      wind_speed: 10
    required:
    - temp
  WeatherWeatherQueryOKResponseBody:
    title: WeatherWeatherQueryOKResponseBody
    type: object
    properties:
      feels_like:
        type: number
        example: 22.1
        format: double
      pressure:
        type: integer
        example: 1024
        format: int64
      temp:
        type: number
        example: 23.4
        format: double
      wind_speed:
        type: integer
        example: 10
        format: int64
    example:
      feels_like: 22.1
      pressure: 1024
      temp: 23.4
      wind_speed: 10
    required:
    - temp
  WeatherWeatherQueryRequestBody:
    title: WeatherWeatherQueryRequestBody
    type: object
    properties:
      lat:
        type: number
        description: Latitude coordinate of location.
        example: 51.50853
        format: double
      lon:
        type: number
        description: Longitude coordinate of location.
        example: -0.12574
        format: double
      units:
        type: string
        description: Units of measurement. Possible values are 'standard', 'metric'
          or 'imperial'.
        example: metric
    example:
      lat: 51.50853
      lon: -0.12574
      units: metric
    required:
    - lat
    - lon
